steps:
- name: Prepare
  image: alpine:3
  commands:
    - chmod +x notify.sh
  when:
    branch:
    - ${CI_REPO_DEFAULT_BRANCH}
    event:
    - tag
    - manual

- name: Build & publish
  image: woodpeckerci/plugin-docker-buildx:5.1.0
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    registry: ghcr.io
    repo: ghcr.io/dhandspikerwade/woodpecker-plugin-ha-notify
    tags:
      - latest
      - 1
      - ${CI_COMMIT_TAG}
    default_labels: false
    dry_run: false
    pull_image: true
    platforms: linux/amd64,linux/arm64,linux/arm/v7
  when:
    branch:
    - ${CI_REPO_DEFAULT_BRANCH}
    event:
    - tag

- name: notify
  image: ghcr.io/dhandspikerwade/woodpecker-plugin-ha-notify:1.0.2
  settings:
    host:
      from_secret: homeassistant_host
    token:
      from_secret: homeassistant_token
    notify_id:
      from_secret: homeassistant_notify
    status: success # Assume if we've gotten here it's a pass
  when:
    - branch:
      - ${CI_REPO_DEFAULT_BRANCH}
      event:
      - tag
      - manual